name: gitlab-cli # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: GitLab CLI simple interface # 79 char long summary
description: |
  GitLab CLI simple interface. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  gitlab-cli:
    command: bin/gitlab-cli
    plugs:
      - home
      - network

parts:
  gitlab-cli:
    npm-node-version: 20.10.0
    npm-include-node: true
    plugin: npm
    source: .


